{{- if .Values.ingress.enabled }}
apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    "app.kubernetes.io/name": {{ .Release.Name }}
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: {{ .Release.Name }}
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.servicePort }}
{{- if .Values.ingress.path }}
        path: {{ .Values.ingress.path }}
{{- end -}}
{{- if .Values.ingress.hostName }}
    host: {{ .Values.ingress.hostName | quote }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}
